// Test lead data for development
export const testLeads = [
  {
    leadId: 'LEAD_2026_0001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    phone: '+919876543210',
    company: 'Tech Solutions Pvt Ltd',
    projectType: 'Corporate Interior',
    budget: 5000000,
    timeline: 'urgent',
    location: 'Mumbai',
    message: 'Need complete office interior for 10,000 sq ft space. Urgent requirement.',
    source: 'IndiaMART',
    status: 'hot',
    aiScore: 95,
    aiInsights: 'High budget, urgent timeline, corporate client',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    leadId: 'LEAD_2026_0002',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+919876543211',
    company: 'Sharma Residence',
    projectType: 'Residential Interior',
    budget: 2000000,
    timeline: '2-3 months',
    location: 'Delhi',
    message: 'Looking for complete home interior design for 3BHK apartment.',
    source: 'Website',
    status: 'warm',
    aiScore: 65,
    aiInsights: 'Good budget, flexible timeline',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
  },
  {
    leadId: 'LEAD_2026_0003',
    name: 'Amit Patel',
    email: 'amit.patel@example.com',
    phone: '+919876543212',
    company: 'Patel Industries',
    projectType: 'Modular Kitchen',
    budget: 500000,
    timeline: '1 month',
    location: 'Ahmedabad',
    message: 'Need modular kitchen for new home.',
    source: 'JustDial',
    status: 'warm',
    aiScore: 55,
    aiInsights: 'Medium budget, clear requirement',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    leadId: 'LEAD_2026_0004',
    name: 'Sunita Verma',
    email: 'sunita.verma@example.com',
    phone: '+919876543213',
    company: null,
    projectType: 'Residential Interior',
    budget: 300000,
    timeline: 'flexible',
    location: 'Pune',
    message: 'Just checking prices for bedroom interior.',
    source: 'Google',
    status: 'cold',
    aiScore: 25,
    aiInsights: 'Low budget, exploratory inquiry',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000), // 2 days ago
  },
  {
    leadId: 'LEAD_2026_0005',
    name: 'Vikram Singh',
    email: 'vikram.singh@defense.gov.in',
    phone: '+919876543214',
    company: 'Ministry of Defense',
    projectType: 'Government Projects',
    budget: 15000000,
    timeline: 'urgent',
    location: 'New Delhi',
    message: 'GeM tender for defense office interior. Need immediate quotation.',
    source: 'GeM Portal',
    status: 'hot',
    aiScore: 98,
    aiInsights: 'Government client, very high budget, urgent',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
  },
];
